version: '3'

services:
  ransomware-tracker:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"  # noVNC port for browser display
      - "9050:9050"  # Tor SOCKS port 
      - "9051:9051"  # Tor control port
    volumes:
      - ./data:/app/data  # Mount data directory for JSON access
    environment:
      - DISPLAY=:1
      - TZ=UTC
    restart: unless-stopped