name: AI Processing Workflow

on:
  # Listen for repository dispatch events
  repository_dispatch:
    types: [run-ai-processing]
  # Also allow manual triggering
  workflow_dispatch:

jobs:
  process-ai:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Get the latest code including the commits from the scrape workflow
          ref: main  # or your default branch
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Create directories
        run: |
          mkdir -p data/AI logs

      - name: Extract AI fields
        run: |
          echo "Running extract_ai_fields.py..."
          python tracker/AI/extract_ai_fields.py --output data/AI
          echo "Extraction completed"
        
      - name: Run domain enrichment
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: |
          echo "Running domain_enrichment.py..."
          python tracker/AI/domain_enrichment.py --yes --output data/AI
          echo "Domain enrichment completed"

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add -A data/AI/
          
          if ! git diff --staged --quiet; then
            git commit -m "Auto-update AI data"
            git push
          else
            echo "No changes to commit"
          fi