name: AI Processing Workflow

on:
  schedule:
    # Run every 48 hours (at 12:00 UTC every other day)
    - cron: '0 12 */2 * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  process-ai:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required to push changes back to the repository
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1  # Shallow clone for speed

      # Use pre-installed Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'  # Use action's built-in caching

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # Install minimum required packages
            pip install requests
          fi

      # Create directories if needed
      - name: Prepare directories
        run: |
          mkdir -p data/processed logs AI

      # Run the AI processing workflow
      - name: Run AI processing
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: |
          python tracker/processing/run_ai_processing.py

      # Commit changes if any
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add AI data files
          git add -A AI/
          
          # Check if there are changes to commit
          if ! git diff --staged --quiet; then
            git commit -m "Auto-update AI data from AI processing workflow"
            git push
          else
            echo "No changes to commit"
          fi