name: AI Processing Workflow

on:
  schedule:
    # Run every 48 hours
    - cron: '0 12 */2 * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  process-ai:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Create directories
        run: |
          mkdir -p data/AI logs

      - name: Run AI processing with GitHub flag
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
        run: |
          python tracker/processing/run_ai_processing.py --github

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          git add -A data/AI/
          
          if ! git diff --staged --quiet; then
            git commit -m "Auto-update AI data"
            git push
          else
            echo "No changes to commit"
          fi