name: Ransomware Tracker Scraping

on:
  schedule:
    # Run every 6 hours
    - cron: '0 */6 * * *'
  # Allow manual triggering
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Tor
        run: |
          sudo apt-get update
          sudo apt-get install -y tor
          sudo service tor start
          # Verify Tor is running
          sleep 5  # Give Tor time to start
          netstat -tulpn | grep 9050 || echo "Warning: Tor might not be running on port 9050"

      - name: Install Firefox and Geckodriver for Selenium
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          # Install a compatible geckodriver version (0.36.0) for Firefox 136
          wget https://github.com/mozilla/geckodriver/releases/download/v0.36.0/geckodriver-v0.36.0-linux64.tar.gz
          tar -xzf geckodriver-v0.36.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
          geckodriver --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Configure for GitHub Actions
        run: |
          # Create scraping_config.json to disable HTML snapshots
          mkdir -p config/code
          echo '{
            "snapshots": {
              "save_html": false,
              "max_snapshots_per_site": 5,
              "cleanup_old_snapshots": true
            },
            "scheduling": {
              "frequency_hours": 6,
              "randomize_start_time": true
            }
          }' > config/code/scraping_config.json
          
          # Create proxy_config.json to use GitHub Actions Tor
          echo '{
            "proxy": {
              "type": "socks",
              "host": "127.0.0.1",
              "port": 9050,
              "remote_dns": true
            },
            "tor": {
              "auto_start": false
            }
          }' > config/code/proxy_config.json
          
          # Create browser_config.json
          echo '{
            "timing": {
              "min_wait_time": 10,
              "max_wait_time": 20,
              "tor_check_wait_time": 3,
              "page_load_timeout": 120
            },
            "anti_bot": {
              "enabled": true,
              "randomize_timing": true
            },
            "user_agent": "Mozilla/5.0 (Windows NT 10.0; rv:102.0) Gecko/20100101 Firefox/102.0"
          }' > config/code/browser_config.json

      - name: Run scraper
        run: |
          # Create necessary directories
          mkdir -p data/output
          mkdir -p data/html_snapshots
          
          # Run the scraper
          cd tracker
          python main.py

      - name: Commit and push if there are changes
        run: |
          # Clean up geckodriver tarball to avoid tracking it
          rm -f geckodriver-*.tar.gz
          
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add all changes in both config and data directories
          git add -A config/code/
          git add -A data/
          
          # Check if there are changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Auto-update data and config from scheduled scrape"
            git push
          fi